name: Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print
        shell: bash
        run: |
          echo {{ github.event_name }}
          echo {{ github.ref }}
